{
 "title": "Linkerd Route Dashboard",
 "description": "Latency, SR, RPS, by deployment and route",
 "time": { "from": "2020-03-08T07:39:21.984Z", "to": "2020-03-08T10:03:17.105Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(route_response_total, namespace)"
   },
   {
    "name": "dst",
    "query": "label_values(route_response_total{namespace=~\"$namespace\"}, dst)"
   },
   {
    "name": "app",
    "query": "label_values(route_response_total{namespace=~\"$namespace\", dst=~\"$dst\"}, app)"
   },
   {
    "name": "route",
    "query": "label_values(route_response_total{app=~\"$app\", namespace=~\"$namespace\", dst=~\"$dst\"}, rt_route)"
   },
   {
    "name": "status_code",
    "query": "label_values(route_response_total{app=~\"$app\", namespace=~\"$namespace\", rt_route=~\"$route\", dst=~\"$dst\"}, status_code)"
   },
   { "name": "percentile", "query": "50,95,99" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentile, sum(irate(route_response_latency_ms_bucket{namespace=~\"$namespace\", app=~\"$app\", rt_route=~\"$route\", dst=~\"$dst\", status_code=~\"$status_code\"}[1m])) by (le, rt_route, dst, app, status_code))",
     "legendFormat": "src={{app}}, {{status_code}}, {{rt_route}}, dst={{dst}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(route_response_total{classification=\"success\", namespace=~\"$namespace\", app=~\"$app\", rt_route=~\"$route\", dst=~\"$dst\"}[1m])) by (rt_route, dst, app) / sum(irate(route_response_total{namespace=~\"$namespace\", app=~\"$app\", rt_route=~\"$route\", dst=~\"$dst\"}[1m])) by (rt_route, dst, app)",
     "legendFormat": "src={{app}}, {{rt_route}}, dst={{dst}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(route_response_total{app=~\"$app\", namespace=~\"$namespace\", rt_route=~\"$route\", dst=~\"$dst\", status_code=~\"$status_code\"}[1m])) by (rt_route, dst, app, status_code)",
     "legendFormat": "src={{app}}, {{status_code}}, {{rt_route}}, dst={{dst}}"
    }
   ]
  }
 ]
}